language: java
jdk:
  - openjdk8
services:
  - mysql
script: "ant all"
sudo: required
before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -u root -e 'CREATE DATABASE LAS2PEERMON;'
  - mysql -u root LAS2PEERMON < bin/db.sql
after_success:
  - bash <(curl -s https://codecov.io/bash)
