name: Docker Build and Push

on:
  push:
    branches: [master, develop, build-test]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare MySQL database
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'LAS2PEERMON' # Optional, default value is "test". The specified database which will be created
          mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: 'password' # Required if "mysql user" exists. The password for the "mysql user"
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Create directories
        run: cd app && mkdir measure_catalogs && mkdir success_models
      - name: Grant Gradle permissions
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test --info 
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build the Docker image
        run: |
          docker build -t registry.tech4comp.dbis.rwth-aachen.de/rwthacis/mobsos-success-modeling:${{ steps.extract_branch.outputs.branch }} .
      - name: Push to registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PW: ${{ secrets.DOCKER_PW }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PW registry.tech4comp.dbis.rwth-aachen.de
          docker push registry.tech4comp.dbis.rwth-aachen.de/rwthacis/mobsos-success-modeling:${{ steps.extract_branch.outputs.branch }}
