name: Docker Build and Push

on:
  push:
    branches: [master, develop, build-test]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: LAS2PEERMON
          MYSQL_ROOT_PASSWORD: rootpw

    steps:
      - name: Verify MySQL connection
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
            sleep 1
          done
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Grant Gradle permissions
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew clean build --info 
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build the Docker image
        run: |
          docker build -t registry.tech4comp.dbis.rwth-aachen.de/rwthacis/mobsos-success-modeling:${{ steps.extract_branch.outputs.branch }} .
      - name: Push to registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PW: ${{ secrets.DOCKER_PW }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PW registry.tech4comp.dbis.rwth-aachen.de
          docker push registry.tech4comp.dbis.rwth-aachen.de/rwthacis/mobsos-success-modeling:${{ steps.extract_branch.outputs.branch }}
